language: node_js
node_js:
  - lts/*
install:
  - npm install
before_script:
  - npm rebuild node-sass
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_ACCESS_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: docs_dist
  on:
    branch: master
    node: 'lts/*'
